SchoolWeb_Lo/SchoolWeb_Lo/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import logout_then_login
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('core.urls')),
    url(r'^inscripcion/', include (('apps.inscripcion.urls', 'inscripcion'), namespace='inscripcion')),  
    url(r'^alumno/', include ('apps.alumno.urls')),
    url(r'^admision/', include ('apps.admision.urls')),
    url(r'^documento/', include(('apps.documento.urls', 'documento'), namespace='documento')),      
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^accounts/login/', LoginView.as_view(), name='login'),
    url(r'^logout/', logout_then_login, name='logout'),    
]

SchoolWeb_Lo/apps/inscripcion/urls.py
from django.conf.urls import url, include
from apps.inscripcion.views import confirmacion, inscripcionList, inscripcionCreate, inscripcionUpdate, inscripcionDelete
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', confirmacion, name='confirmacion'),
    url(r'^nuevo/$', login_required(inscripcionCreate.as_view()), name='inscripcion'),
    url(r'^listar/$', inscripcionList.as_view(), name='inscripcion_listar'),
    url(r'^editar/(?P<pk>\d+)/$', inscripcionUpdate.as_view(), name='inscripcion_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', inscripcionDelete.as_view(), name='inscripcion_eliminar'),
]

SchoolWeb_Lo/core/urls.py
from django.urls import path
from .views import home, nosotros, comunidad, admision, documento, inscripcion

urlpatterns = [
    path('', home, name="home"),
    path('nosotros/', nosotros, name="nosotros"),
    path('comunidad/', comunidad, name="comunidad"),
    path('admision/', admision, name="admision"),
    path('documento/', documento, name="documento"),
    path('inscripcion/', inscripcion, name="inscripcion"),
]

SchoolWeb_Lo/login_tanya/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
]

SchoolWeb_Lo/apps/inscripcion/models.py
from django.db import models
from datetime import datetime
from apps.alumno.models import Alumno

# Create your models here.

class Inscripcion(models.Model):
  fechaInscrip = models.DateTimeField(default=datetime.now, null=False, blank=False)
  rut = models.ForeignKey(Alumno, null=True, blank=False, on_delete=models.CASCADE)
  NOMBRE=(
     ('Pintura','Pintura'),
     ('Musica','Musica'),
     ('Contabilidad','Contabilidad'),
     ('Diseño Web','Diseño Web'),
     ('Escritura','Escritura'),               
   )
  nombre = models.CharField(max_length=15, choices=NOMBRE, default='Pintura')

  def __str__(self):
     return '{} {}'.format(self.rut, self.nombre)

SchoolWeb_Lo/core/models.py
from django.db import models

# Create your models here.

SchoolWeb_Lo/apps/inscripcion/forms.py
from django import forms
from apps.inscripcion.models import Inscripcion


class InscripcionForm(forms.ModelForm):

    class Meta: 
        model = Inscripcion
        
        fields = [
            'fechaInscrip',
            'rut',
            'nombre',
        ]

        labels ={
            'fechaInscrip': 'Fecha',
            'rut': 'Alumno',
            'nombre': 'Nombre del Curso',  
        }

        widgets = {
            'fechaInscrip': forms.DateTimeInput(attrs={'class':'form-control'}),
            'rut': forms.Select(attrs={'class':'form-control'}),
            'nombre': forms.Select(attrs={'class':'form-control'}),
        }

SchoolWeb_Lo/apps/inscripcion/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from apps.inscripcion.forms import InscripcionForm
from apps.inscripcion.models import Inscripcion
from datetime import datetime
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.

def confirmacion(request):
    return render(request,'inscripcion/confirmacion.html')

def inscripcion_view(request):
    if request.method == 'POST':
        form = InscripcionForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request,'inscripcion:confirmacion')
    else:
        form = InscripcionForm()
        return render(request, 'inscripcion/inscripcion.html', {'form':form})      

def inscripcion_delete(request, id_inscripcion):
    inscripcion= Inscripcion.objects.get(id_inscripcion)
    if request.method == 'POST':
        inscripcion.delete()
        return redirect(request,'inscripcion:inscripcion_listar')
    return render(request, 'inscripcion/inscripcion_delete.html', {'inscripcion':inscripcion})            

class inscripcionList (ListView):
    model = Inscripcion
    template_name = 'inscripcion/inscripcion_listar.html'

#class inscripcionCreate (CreateView):
    #model = Inscripcion
    #form_class = InscripcionForm
    #template_name = 'inscripcion/inscripcion.html'
    #success_url = reverse_lazy('inscripcion:inscripcion_listar')

class inscripcionCreate (CreateView):
    model = Inscripcion
    form_class = InscripcionForm
    template_name = 'inscripcion/inscripcion.html'
    success_url = reverse_lazy('inscripcion:inscripcion_listar')
    
class inscripcionUpdate (UpdateView):
    model = Inscripcion
    form_class = InscripcionForm
    template_name = 'inscripcion/inscripcion.html'
    success_url = reverse_lazy('inscripcion:inscripcion_listar')
    
class inscripcionDelete (DeleteView):
    model = Inscripcion
    template_name = 'inscripcion/inscripcion_delete.html'
    success_url = reverse_lazy('inscripcion:inscripcion_listar')

SchoolWeb_Lo/core/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'core/home.html')

def nosotros(request):
    return render(request, 'core/nosotros.html')

def comunidad(request):
    return render(request, 'core/comunidad.html')

def admision(request):
    return render(request, 'core/admision.html')

def documento(request):
    return render(request, 'core/documento.html')

def inscripcion(request):
    return render(request, 'core/inscripcion.html')     
     

SchoolWeb_Lo/core/templates/inscripcion/confirmacion.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="container portfolio-item">        
        <h4 class= "exito">Inscripcion Exitosa</h4>  
    </div>
{% endblock %}

SchoolWeb_Lo/core/templates/inscripcion/inscripcion.html
<!DOCTYPE html>
<html lang="es">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Colegio Humbolt-Excelencia en Educación</title>

 <!-- Bootstrap core CSS -->
 {% load static %}
 <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

 <!-- Custom fonts for this template -->
 {% load static %}
 <script src="https://kit.fontawesome.com/20ca054ebc.js" crossorigin="anonymous"></script>
 <link href="{% static 'core/vendor/fontawesome-free/css/all.min.css' %} rel="stylesheet" type="text/css">
 <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
 <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
 <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
 <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

 <!-- Custom styles for this template -->
 {% load static %}
 <link href="{% static 'core/css/nosotros.css' %}" rel="stylesheet">

</head>

<body id="page-top">

 <!-- Navigation -->
 <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">Colegio Humbolt</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav text-uppercase ml-auto">
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'home' %}">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'nosotros' %}"">Nosotros</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'comunidad' %}">Comunidad</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger"  href="{% url 'admision' %}"">Admisión 2020</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'documento:documento' %}">Solicitudes</a>
        </li>
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style='color:white' href="{% url 'inscripcion:inscripcion' %}">Inscripcion</a>
        </li>

        <li class="nav-item">
            {% load static %}
          <a class="nav-link js-scroll-trigger" href="{% url 'login' %}"><i class="fas fa-user usuario" style="color:white"></i></a>
        </li>

        <li class="nav-item">
          {% load static %}
        <a class="nav-link js-scroll-trigger" href="{% url 'logout' %}"><i class="fas fa fa-window-close" style="color:white"></i></a>
      </li>



      </ul>
    </div>
  </div>
</nav>


<!--Login con validación-->
<div id="modalPassword" class="modal fade" tabindex="-1" role="dialog"  aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3>Recuperar Contraseña</h3>
        <button type="button" class="close font-weight-light" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <div class="modal-body">
        <p>Se enviará la contraseña a tu mail.</p>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" id="enviar">Enviar</button>
        <button class="btn btn-primary" data-dismiss="modal" id="cerrar" aria-hidden="true">Cerrar</button>
      </div>
    </div>
  </div>
</div>

<!-- Header -->
<header class="masthead">
  <img class= "masthead" src="{% static 'core/img/principal6.jpg' %}" width="100%" height="900px">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in"></div>

      <div class="botones" >
        <div class="row">
          <div class="col-lg-12 text-center">

          </div>
        </div>
      </div>
    </div> 
  </div>
</header>

{% block content %}     

    <div class="container col-lg-8">
        <form method="post" class="form-group was-validated page-section">
          <h3>Inscripción de cursos optativos</h3>
          <br>
            {% csrf_token %}
                      <div class="col-lg-4">
                <button type="submit" id="enviar-pos" class="btn btn-primary btn-lg enviar">Inscribir</button>
            </div>
        </form>
    </div>    
{% endblock %}

    <!-- Contact -->
    <section class="page-section" id="contact">
            <div class="container">
              <div class="row">
                <div class="col-lg-12 text-center">
                  <h2 class="section-heading text-uppercase">Contactanos</h2>
                  <h3 class="section-subheading text-muted">Envianos un mensaje para poder ayudarte.</h3>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-12">
                  <form id="contactForm" name="sentMessage" novalidate="novalidate">
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <input class="form-control" id="name" type="text" placeholder="Nombre *" required="required" data-validation-required-message="Ingresar nombre.">
                          <p class="help-block text-danger"></p>
                        </div>
                        <div class="form-group">
                          <input class="form-control" id="email" type="email" placeholder="Email *" required="required" data-validation-required-message="Ingresa tu correo electrónico.">
                          <p class="help-block text-danger"></p>
                        </div>
                        <div class="form-group">
                          <input class="form-control" id="phone" type="tel" placeholder="Teléfono *" required="required" data-validation-required-message="Ingresa número de teléfono.">
                          <p class="help-block text-danger"></p>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <textarea class="form-control" id="message" placeholder="Mensaje *" required="required" data-validation-required-message="Ingresar Mensaje."></textarea>
                          <p class="help-block text-danger"></p>
                        </div>
                      </div>
                      <div class="clearfix"></div>
                      <div class="col-lg-12 text-center">
                        <div id="success"></div>
                        <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase enviar" type="submit">Enviar</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </section>
        
              <!-- Footer -->
              <footer class="footer">
                <div class="container">
                  <div class="row align-items-center">
                    <div class="col-md-4">
                      <span class="copyright">Copyright &copy; Your Website 2019</span>
                    </div>
                    <div class="col-md-4">
                      <ul class="list-inline social-buttons">
                        <li class="list-inline-item">
                          <a href="#">
                            <i class="fab fa-twitter"></i>
                            
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a href="#">
                            <i class="fab fa-facebook-f"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a href="#">
                            <i class="fab fa-linkedin-in"></i>
                          </a>
                        </li>
                      </ul>
                    </div>
                    <div class="col-md-4">
                      <ul class="list-inline quicklinks">
                        <li class="list-inline-item">
                          <a href="#">Privacy Policy</a>
                        </li>
                        <li class="list-inline-item">
                          <a href="#">Terms of Use</a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </footer>
        
              <!-- Bootstrap core JavaScript -->
              {% load static %}
              <script src="{% static 'corevendor/jquery/jquery.min.js' %}"></script>
              {% load static %}
              <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
            
              <!-- Plugin JavaScript -->
              {% load static %}
              <script src="{% static 'core/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
            
              <!-- Contacto JavaScript -->
              {% load static %}
              <script src="{% static 'core/js/jqBootstrapValidar.js' %}"></script>
              {% load static %}
              <script src="{% static 'core/js/contacto.js' %}"></script>
            
              <!-- NavBar -->
              {% load static %}
              <script src="{% static 'core/js/colegio.js' %}"></script>
        
            </body>
        
            </html>

SchoolWeb_Lo/core/templates/inscripcion/inscripcion_delete.html
{% extends 'base/base.html' %}

{% block content %}     

    <div class="container col-lg-8">
        <form method="post" class="form-group was-validated page-section">
            {% csrf_token %}
            <h3>Desea Eliminar la Inscripción número {{ object.id }} {{ object.nombre }}?</h3>
            <br>
        
            <div class="col-lg-4">
                <button type="submit" id="enviar-pos" class="btn btn-primary btn-lg enviar">Si Eliminar</button>
                <a class="btn btn-default" href="{% url 'inscripcion:inscripcion_listar'%}">Cancelar</a>
            </div>
        </form>
    </div>    
{% endblock %}

SchoolWeb_Lo/core/templates/inscripcion/inscripcion_listar.html
{% extends 'base/base.html' %}

{% block content %}     

    <div class="container table-responsive table-responsive-ms">
        <h3>Cursos opcionales inscritos</h3>
        <br>
        <table class="table table-striped">
            <thead>
                <th>Id</th>
                <th>Fecha Inscripcion</th>
                <th>Rut</th>
                <th>Curso</th>
                <th>Acciones</th>              
            </thead>

            <tbody>
                {% if object_list %}
                {% for inscripcion in object_list %}

                <tr>                        
                    <td>{{ inscripcion.id}}</td>
                    <td>{{ inscripcion.fechaInscrip}}</td>
                    <td>{{ inscripcion.rut}}</td>
                    <td>{{ inscripcion.nombre}}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'inscripcion:inscripcion_editar' inscripcion.id %}">Editar</a>
                        <a class="btn btn-danger" href="{% url 'inscripcion:inscripcion_eliminar' inscripcion.id %}">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                    <h1>No hay cursos inscritos</h1>
                {% endif %}
            </tbody>
        </table>
    </div>    
{% endblock %}